export const types = {
    FETCH_EPISODE: 'FETCH_EPISODE',
    SET_EPISODE: 'SET_EPISODE',
    MERGE_EPISODE: 'MERGE_EPISODE',
    SET_PRELOADED: 'SET_PRELOADED',
    PRELOAD: 'PRELOAD',
    SET_CHARACTER: 'SET_CHARACTER',
    MERGE_CHARACTER: 'MERGE_CHARACTER'
}
