export const types = {
    FETCH_EPISODE: 'FETCH_EPISODE',
    SET_EPISODE: 'SET_EPISODE',
    MERGE_EPISODE: 'MERGE_EPISODE',
    MERGE_EPISODES: 'MERGE_EPISODES',
    SET_PRELOADED: 'SET_PRELOADED',
    PRELOAD_CHARACTER: 'PRELOAD_CHARACTER',
    PRELOAD: 'PRELOAD',
    SET_CHARACTER: 'SET_CHARACTER',
    MERGE_CHARACTER: 'MERGE_CHARACTER',
    FETCH_CHARACTER: 'FETCH_CHARACTER'
}
