name: Deploy to Firebase Hosting on PR
'on': pull_request

env:
  VUE_APP_ALGOLIA_APP_ID: '${{ secrets.ALGOLIA_APP_ID }}'
  VUE_APP_ALGOLIA_API_KEY: '${{ secrets.ALGOLIA_API_KEY }}'

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_OFFICE_0X3401 }}'
          projectId: the-office-0x3401
